#!/bin/bash

# TODO check later for headers in the dependencies; conditional compilation
# may give false results

pushd $(git rev-parse --show-toplevel) 1> /dev/null
retcode=0
for f in src/*.cpp ; do
    f=$(basename $f)
    if ! grep -q "\$(DSTDIR)/${f%.cpp}.o" namd/colvars/src/Makefile.namd ; then
        echo "Error: ${f%.cpp}.o entry missing from namd/colvars/src/Makefile.namd" >&2
        retcode=1
    fi
    if ! grep -q "obj/${f%.cpp}.o" namd/colvars/Make.depends ; then
        echo "Error: obj/${f%.cpp}.o missing from namd/colvars/Make.depends" >&2
        retcode=1
    fi
    vmd_source=${f%.cpp}.C
    if ! grep -q ${vmd_source} vmd/src/colvars_files.pl ; then
        echo "Error: ${vmd_source} missing from vmd/src/colvars_files.pl" >&2
        retcode=1
    fi
    if ! grep -q ${f} lammps/lib/colvars/Makefile.common ; then
        echo "Error: ${f} missing from lammps/lib/colvars/Makefile.common" >&2
        retcode=1
    fi
done
popd 1> /dev/null
exit ${retcode}
