#!/bin/bash

# TODO check later for headers in the dependencies; conditional compilation
# may give false results

echo "Checking Colvars build recipes for VMD"

pushd $(git rev-parse --show-toplevel) 1> /dev/null
retcode=0
for f in src/colvar*.cpp src/colvar*.h ; do
    f=$(basename $f)
    extension=${f#*.}
    if [ ${extension} = 'cpp' ] ; then
        prefix=${f%.cpp}
        vmd_source=${prefix}.C
    else
        prefix=${f%.h}
        vmd_source=${f}
    fi
    if ! grep -q ${vmd_source} vmd/src/colvars_files.pl ; then
        echo "Error: ${vmd_source} missing from vmd/src/colvars_files.pl" >&2
        retcode=1
    fi
done
popd 1> /dev/null
exit ${retcode}
