#!/bin/bash

# TODO check later for headers in the dependencies; conditional compilation
# may give false results

echo "Checking Colvars build recipes for NAMD and VMD, which do not use CMake"

pushd $(git rev-parse --show-toplevel) 1> /dev/null
retcode=0
for f in src/colvar*.cpp src/colvar*.h ; do
    f=$(basename $f)
    extension=${f#*.}
    if [ ${extension} = 'cpp' ] ; then
        prefix=${f%.cpp}
        vmd_source=${prefix}.C
        if ! grep -q "obj/${prefix}.o" namd/colvars/Make.depends ; then
            echo "Warning: obj/${prefix}.o missing from namd/colvars/Make.depends" >&2
        fi
        if ! grep -q "\$(DSTDIR)/${prefix}.o" namd/colvars/src/Makefile.namd ; then
            echo "Error: ${prefix}.o entry missing from namd/colvars/src/Makefile.namd" >&2
            retcode=1
        fi
    else
        prefix=${f%.h}
        vmd_source=${f}
        if ! grep -q "colvars/src/${f}" namd/colvars/Make.depends ; then
            echo "Warning: colvars/src/${f} missing from namd/colvars/Make.depends" >&2
        fi
    fi
    if ! grep -q ${vmd_source} vmd/src/colvars_files.pl ; then
        echo "Error: ${vmd_source} missing from vmd/src/colvars_files.pl" >&2
        retcode=1
    fi
done
popd 1> /dev/null
exit ${retcode}
