#!/bin/bash
#
# Remove all trailing whitespace in the files about to be committed.

for f in $(git status --porcelain | \
                  sed -n -e 's/^M \+\(.*\.\(cpp\|h\|C\)\)/\1/p')
do \
  sed -i -e 's/ \+$//' -e 's/	\+$//' $f
  git add $f
done

exit 0
