#!/bin/bash
#
# This hook will do some automatic checks and updates before a commit.

################################################################################
# Task 1a: update the Colvars module version string if a file in the src/
#          directory is about to be committed. Do not update it, if current.

if git status --porcelain | grep -q '^M \+src/'
then
  datestr=$(date +'%Y-%m-%d')
  datestrtex=$(date +'%Y-%m-%d')
  branch=`git rev-parse --abbrev-ref HEAD`
  if test "${branch}" != "master"
  then
    datestrtex="${datestr}\\_${branch}"
    datestr="${datestr}_${branch}"
  fi
  prevstr=$(sed -n -e 's/^#define COLVARS_VERSION "\(.*\)".*/\1/p' src/colvars_version.h)
  if test "${prevstr}" = "${datestr}"
  then
    echo "Keeping Colvars version string at: ${prevstr}"
  else
    echo "Updating Colvars version string from ${prevstr} to ${datestr}"
    sed -i -e "s/^#define COLVARS_VERSION.*/#define COLVARS_VERSION \"${datestr}\"/" src/colvars_version.h
    echo -E "\newcommand{\cvversion}{${datestrtex}}" > doc/cv_version.tex
    git add src/colvars_version.h doc/cv_version.tex
  fi
fi

################################################################################
# Task 1b: update the respective colvarproxy version string if a file in the
#          vmd/src, namd/src, or lammps/src directory is about to be committed.
#          Do not update it, if current.

if git status --porcelain | grep -q '^M \+lammps/src/'
then
  datestr=$(date +'%Y-%m-%d')
  branch=`git rev-parse --abbrev-ref HEAD`
  if test "${branch}" != "master"
  then
    datestr="${datestr}_${branch}"
  fi
  prevstr=$(sed -n -e 's/^#define COLVARPROXY_VERSION "\(.*\)".*/\1/p' \
            lammps/src/USER-COLVARS/colvarproxy_lammps_version.h)
  if test "${prevstr}" = "${datestr}"
  then
    echo "Keeping LAMMPS Colvars interface version string at: ${prevstr}"
  else
    echo "Updating LAMMPS Colvars interface version string from ${prevstr} to ${datestr}"
    sed -i -e "s/^#define COLVARPROXY_VERSION.*/#define COLVARPROXY_VERSION \"${datestr}\"/" \
       lammps/src/USER-COLVARS/colvarproxy_lammps_version.h
    git add lammps/src/USER-COLVARS/colvarproxy_lammps_version.h
  fi
fi

if git status --porcelain | grep -q '^M \+namd/src/'
then
  datestr=$(date +'%Y-%m-%d')
  branch=`git rev-parse --abbrev-ref HEAD`
  if test "${branch}" != "master"
  then
    datestr="${datestr}_${branch}"
  fi
  prevstr=$(sed -n -e 's/^#define COLVARPROXY_VERSION "\(.*\)".*/\1/p' \
            namd/src/colvarproxy_namd_version.h)
  if test "${prevstr}" = "${datestr}"
  then
    echo "Keeping NAMD Colvars interface version string at: ${prevstr}"
  else
    echo "Updating NAMD Colvars interface version string from ${prevstr} to ${datestr}"
    sed -i -e "s/^#define COLVARPROXY_VERSION.*/#define COLVARPROXY_VERSION \"${datestr}\"/" \
       namd/src/colvarproxy_namd_version.h
    git add namd/src/colvarproxy_namd_version.h
  fi
fi

if git status --porcelain | grep -q '^M \+vmd/src/'
then
  datestr=$(date +'%Y-%m-%d')
  branch=`git rev-parse --abbrev-ref HEAD`
  if test "${branch}" != "master"
  then
    datestr="${datestr}_${branch}"
  fi
  prevstr=$(sed -n -e 's/^#define COLVARPROXY_VERSION "\(.*\)".*/\1/p' \
            vmd/src/colvarproxy_vmd_version.h)
  if test "${prevstr}" = "${datestr}"
  then
    echo "Keeping VMD Colvars interface version string at: ${prevstr}"
  else
    echo "Updating VMD Colvars interface version string from ${prevstr} to ${datestr}"
    sed -i -e "s/^#define COLVARPROXY_VERSION.*/#define COLVARPROXY_VERSION \"${datestr}\"/" \
       vmd/src/colvarproxy_vmd_version.h
    git add vmd/src/colvarproxy_vmd_version.h
  fi
fi

################################################################################
# Task 2: remove all trailing whitespace in the files about to be committed.

for f in $(git status --porcelain | sed -n -e 's/^M \+\(.*\.\(cpp\|h\|C\)\)/\1/p')
do \
  sed -i -e 's/ \+$//' -e 's/	\+$//' $f
  git add $f
done

exit 0
