#!/bin/bash



if [ -z "${1}" ] ; then
    echo "Strip formatting codes from spiff from multiple diff files."
    echo "WARNING: strips underscore characters as well!"
    echo
    echo "Apply a set of diffs to the reference files for a regtest"
    echo "Usage:"
    echo "    $0 diff1 [diff2] [...]"
fi

for file in "${@}" ; do
  base=$(basename "${file}")
  cat "${file}" | \
    tr -cd '\11\12\15\40-\176' | \
    tr -d '_' > /tmp/"${base}" && \
    mv /tmp/"${base}" "${file}" 
done
