.PHONY: all gromacs lammps namd


all: gromacs lammps namd

gromacs:
	./build_tests.sh ../gromacs/tests/library/

lammps:
	./build_tests.sh ../lammps/tests/library/

namd:
	./build_tests.sh ../namd/tests/library/

