# -*- makefile -*- to build Colvars module with GNU compiler

COLVARS_LIB = libcolvars.a
COLVARS_OBJ_DIR =

CXX =		g++
CXXFLAGS =	-O2 -g -Wall -fPIC -funroll-loops
AR =		ar
ARFLAGS =	-rscv
SHELL =		/bin/sh

include Makefile.common

.PHONY: default clean

default: $(COLVARS_LIB) Makefile.lammps

clean:
	-rm $(COLVARS_OBJS) $(COLVARS_LIB)

