# -*- makefile -*-

VERSION = 1.4
ifeq (${DESTINATION},)
DESTINATION = ${HOME}/lib/vmd/plugins/noarch/tcl/cv_dashboard${VERSION}
endif

install:
	mkdir -p ${DESTINATION} && \
	  rsync -avL --delete --exclude=Makefile.local ./ ${DESTINATION}/

