# -*- makefile -*-

VERSION = 1.5
ifeq (${DESTINATION},)
DESTINATION = ${HOME}/lib/vmd/plugins/noarch/tcl/cv_dashboard${VERSION}
endif

install:
	mkdir -p ${DESTINATION} && \
	  rsync -avL --delete --exclude CVS --exclude Root --exclude=Makefile.local ./ ${DESTINATION}/

