# -*- makefile -*-

cat := $(if $(filter $(OS),Windows_NT),type,cat)
VERSION := $(shell $(cat) VERSION)

ifeq (${DESTINATION},)
DESTINATION = ${HOME}/lib/vmd/plugins/noarch/tcl/cv_dashboard${VERSION}
endif

install:
	mkdir -p ${DESTINATION} && \
	  rsync -avL --delete --exclude CVS --exclude Root --exclude=Makefile.local ./ ${DESTINATION}/

