diff --git a/Makefile b/Makefile
index f824e77c..e589a680 100644
--- a/Makefile
+++ b/Makefile
@@ -239,6 +239,7 @@ OBJS = \
 	$(DSTDIR)/GlobalMasterTcl.o \
 	$(DSTDIR)/GlobalMasterSMD.o \
 	$(DSTDIR)/GlobalMasterTMD.o \
+	$(DSTDIR)/GlobalMasterColvars.o \
 	$(DSTDIR)/Matrix4Symmetry.o \
 	$(DSTDIR)/GlobalMasterSymmetry.o \
 	$(DSTDIR)/GlobalMasterFreeEnergy.o \
