diff --git a/Makefile b/Makefile
index 960f7718..85126dff 100644
--- a/Makefile
+++ b/Makefile
@@ -231,6 +231,7 @@ OBJS = \
 	$(DSTDIR)/GlobalMasterTcl.o \
 	$(DSTDIR)/GlobalMasterSMD.o \
 	$(DSTDIR)/GlobalMasterTMD.o \
+	$(DSTDIR)/GlobalMasterColvars.o \
 	$(DSTDIR)/Matrix4Symmetry.o \
 	$(DSTDIR)/GlobalMasterSymmetry.o \
 	$(DSTDIR)/GlobalMasterFreeEnergy.o \
