COLVARSLIB = \
	$(DSTDIR)/colvar.o \
	$(DSTDIR)/colvaratoms.o \
	$(DSTDIR)/colvarbias.o \
	$(DSTDIR)/colvarbias_abf.o \
	$(DSTDIR)/colvarbias_alb.o \
	$(DSTDIR)/colvarbias_histogram.o \
	$(DSTDIR)/colvarbias_meta.o \
	$(DSTDIR)/colvarbias_restraint.o \
	$(DSTDIR)/colvarcomp.o \
	$(DSTDIR)/colvarcomp_angles.o \
	$(DSTDIR)/colvarcomp_coordnums.o \
	$(DSTDIR)/colvarcomp_distances.o \
	$(DSTDIR)/colvarcomp_protein.o \
	$(DSTDIR)/colvarcomp_rotations.o \
	$(DSTDIR)/colvarcomp_gpath.o \
	$(DSTDIR)/colvarcomp_apath.o \
	$(DSTDIR)/colvardeps.o \
	$(DSTDIR)/colvargrid.o \
	$(DSTDIR)/colvarmodule.o \
	$(DSTDIR)/colvarparams.o \
	$(DSTDIR)/colvarparse.o \
	$(DSTDIR)/colvarproxy.o \
	$(DSTDIR)/colvarproxy_replicas.o \
	$(DSTDIR)/colvarscript.o \
	$(DSTDIR)/colvartypes.o \
	$(DSTDIR)/colvarvalue.o
