# List of files for the Colvars module

our ( $colvars_defines );

our ( @colvars_cc );
our ( @colvars_cu );
our ( @colvars_ccpp );
our ( @colvars_h );

$colvars_defines = " -DVMDCOLVARS";

@colvars_cc      = ();
@colvars_cu      = ();
@colvars_ccpp    = ('colvaratoms.C',
                    'colvarbias.C',
                    'colvarbias_abf.C',
                    'colvarbias_alb.C',
                    'colvarbias_histogram.C',
                    'colvarbias_meta.C',
                    'colvarbias_restraint.C',
                    'colvarbias_histogram_reweight_amd.C',
                    'colvar.C',
                    'colvarcomp_neuralnetwork.C',
                    'colvar_neuralnetworkcompute.C',
                    'colvarcomp.C',
                    'colvarcomp_alchlambda.C',
                    'colvarcomp_angles.C',
                    'colvarcomp_apath.C',
                    'colvarcomp_combination.C',
                    'colvarcomp_coordnums.C',
                    'colvarcomp_distances.C',
                    'colvarcomp_gpath.C',
                    'colvarcomp_protein.C',
                    'colvarcomp_rotations.C',
                    'colvarcomp_volmaps.C',
                    'colvardeps.C',
                    'colvargrid.C',
                    'colvarmodule.C',
                    'colvarparams.C',
                    'colvarparse.C',
                    'colvarproxy.C',
                    'colvarproxy_io.C',
                    'colvarproxy_replicas.C',
                    'colvarproxy_volmaps.C',
                    'colvarproxy_tcl.C',
                    'colvarproxy_vmd.C',
                    'colvarscript.C',
                    'colvarscript_commands.C',
                    'colvarscript_commands_bias.C',
                    'colvarscript_commands_colvar.C',
                    'colvartypes.C',
                    'colvarvalue.C',
                    'nr_jacobi.C');
@colvars_h    =    ('colvar_UIestimator.h',
                    'colvar_arithmeticpath.h',
                    'colvar_geometricpath.h',
                    'colvar_neuralnetworkcompute.h',
                    'colvaratoms.h',
                    'colvarbias.h',
                    'colvarbias_abf.h',
                    'colvarbias_alb.h',
                    'colvarbias_histogram.h',
                    'colvarbias_histogram_reweight_amd.h',
                    'colvarbias_meta.h',
                    'colvarbias_restraint.h',
                    'colvarcomp.h',
                    'colvardeps.h',
                    'colvargrid.h',
                    'colvar.h',
                    'colvarmodule.h',
                    'colvarmodule_refs.h',
                    'colvarmodule_utils.h',
                    'colvarparams.h',
                    'colvarparse.h',
                    'colvarproxy.h',
                    'colvarproxy_io.h',
                    'colvarproxy_tcl.h',
                    'colvarproxy_vmd.h',
                    'colvarproxy_volmaps.h',
                    'colvarscript.h',
                    'colvarscript_commands.h',
                    'colvarscript_commands_bias.h',
                    'colvarscript_commands_colvar.h',
                    'colvars_version.h',
                    'colvartypes.h',
                    'colvarvalue.h',
                    'nr_jacobi.h');
