name: "Build backends with an updated Colvars module"

on:
  push:
    branches: [ master ]
  pull_request_target:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  backends:
    name: Build backends
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ] #, 'python' ]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.pull_request.head.repo.full_name}}
        ref: ${{github.event.pull_request.head.ref}}

    - name: Configure Ccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.ccache
          ~/ccache_CentOS7-devel
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-
          -build-

    - name: Test build recipes
      run: bash devel-tools/check_build_recipes

    - name: Convert BibTeX references to code
      shell: bash
      working-directory: doc
      run:  make update-code-refs

    - name: Checkout LAMMPS
      uses: actions/checkout@v2
      with:
        repository: 'lammps/lammps'
        ref: 'master'
        path: 'lammps-source'

    - name: Checkout NAMD
      uses: actions/checkout@v2
      with:
        repository: 'Colvars/namd'
        # Per-repository secret (sharing a secret from the org with all
        # repositories turned out to be too complex)
        ssh-key: ${{ secrets.PULL_NAMD_KEY }}
        ref: 'master'
        path: 'namd-source'

    - name: Checkout VMD
      uses: actions/checkout@v2
      with:
        repository: 'Colvars/vmd'
        ssh-key: ${{ secrets.PULL_VMD_KEY }}
        ref: 'master'
        path: 'vmd-source'

    - name: Checkout VMD plugins
      uses: actions/checkout@v2
      with:
        repository: 'Colvars/vmd-plugins'
        ssh-key: ${{ secrets.PULL_VMD_PLUGINS_KEY }}
        ref: 'master'
        path: 'vmd-plugins-source'

    - name: Install build dependencies for backends
      shell: bash
      working-directory: devel-tools
      run: |
        # Singularity 3 hasn't made it to Ubuntu yet: TODO sort this out,
        # or convert existing containers to Docker
        sudo apt-get -y install squashfs-tools containernetworking-plugins
        curl -O http://http.us.debian.org/debian/pool/main/s/singularity-container/singularity-container_3.5.2+ds1-1_amd64.deb
        sudo dpkg -i singularity-container_3.5.2+ds1-1_amd64.deb
        # Pull CentOS 7 container used to build backends
        # (contains OpenMPI, FFTW, Tcl/Tk, Charm++)
        singularity pull CentOS7-devel.sif library://giacomofiorin/default/colvars_development:centos7
        # Get spiff for numerical diffs
        sudo cp -f $(singularity exec CentOS7-devel.sif ./get_spiff) /usr/local/bin

    - name: Update and build LAMMPS
      shell: bash
      run: |
        singularity exec devel-tools/CentOS7-devel.sif ./update-colvars-code.sh lammps-source
        CCACHE_DIR=~/ccache_CentOS7-devel \
        singularity exec devel-tools/CentOS7-devel.sif \
        bash devel-tools/compile-lammps.sh lammps-source

    - name: Run regression tests for library code with LAMMPS
      shell: bash
      working-directory: lammps/tests/library
      run: |
        singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
        ./run_tests.sh ${{github.workspace}}/lammps-source/install/bin/lmp 000_*

    - name: Update and build NAMD
      shell: bash
      run: |
        singularity exec devel-tools/CentOS7-devel.sif ./update-colvars-code.sh namd-source
        CCACHE_DIR=~/ccache_CentOS7-devel \
        singularity exec devel-tools/CentOS7-devel.sif \
        bash devel-tools/compile-namd.sh namd-source

    - name: Run regression tests for library code with NAMD
      shell: bash
      working-directory: namd/tests/library
      run: |
        singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
        ./run_tests.sh ${{github.workspace}}/namd-source/Linux-x86_64-g++.multicore/namd2

    - name: Run regression tests for NAMD interface code
      shell: bash
      working-directory: namd/tests/interface
      run: |
        singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
        ./run_tests.sh ${{github.workspace}}/namd-source/Linux-x86_64-g++.multicore/namd2

    - name: Update and build VMD
      shell: bash
      run: |
        singularity exec devel-tools/CentOS7-devel.sif ./update-colvars-code.sh vmd-source
        CCACHE_DIR=~/ccache_CentOS7-devel \
        singularity exec devel-tools/CentOS7-devel.sif \
        bash devel-tools/compile-vmd.sh vmd-source

    - name: Run regression tests for VMD interface code
      shell: bash
      working-directory: vmd/tests/interface
      run: |
        singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
        ./run_tests.sh ${{github.workspace}}/vmd-source/install/vmd
