name: "Library"

on: [push, pull_request]


jobs:

  basic-checks:

    name: Basic checks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout Colvars
        uses: actions/checkout@v2

      - name: Reload cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-basic-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-basic-

      - name: Install build dependencies for library
        run: |
          sudo apt-get -y install ccache tcl8.6-dev

      - name: Test build recipes
        run: bash devel-tools/check_build_recipes

      - name: Convert BibTeX references to code
        shell: bash
        working-directory: doc
        run: |
          make update-code-refs
          if [ -n "$(git status --porcelain ../src/colvarmodule_refs.h)" ] ; then
              echo "Code citations out of date; please run make update-code-refs in the doc folder" >& 2
              exit 1
          fi

      - name: Build library with CMake
        env:
          CCACHE: ccache
        run: cmake -P devel-tools/build_test_library.cmake

      - name: Check documentation of command-line scripting interface
        shell: bash
        working-directory: doc
        run: |
          make update-cvscript-cmdline-doc
          if [ -n "$(git status --porcelain cvscript-tcl.tex)" ] ; then
              echo "Command-line scripting doc out of date; please run make update-cvscript-cmdline-doc and commit changes" >& 2
              exit 1
          fi


  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    needs: basic-checks
    if: ${{ ! github.event.repository.private }}

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies for library
        run: |
          sudo apt-get -y install tcl8.6-dev
          # OpenMM contains the latest Lepton
          git clone --single-branch --depth=1 https://github.com/openmm/openmm openmm-source

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      - name: Build Colvars library with CMake
        run: cmake -P devel-tools/build_test_library.cmake

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1


  build-linux-x86_64-many:
    name: Linux x86_64 (many compilers)
    runs-on: ubuntu-latest
    needs: basic-checks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    env:
      CCACHE: ccache

    steps:
      - uses: actions/checkout@v2

      - name: Reload ccache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-multiple-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-multiple-

      - name: Get small downloadable packages
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/build-tools-packages'
          ref: 'master'
          path: 'devel-tools/packages'

      - name: Install Singularity
        shell: bash
        working-directory: devel-tools/packages
        run: |
          sudo apt-get -y install squashfs-tools containernetworking-plugins
          sudo dpkg -i singularity_3.8.5-2_amd64.deb

      - name: Get container image of backends' dependencies
        shell: bash
        working-directory: devel-tools
        run: |
          singularity pull CentOS7-devel.sif library://giacomofiorin/default/colvars_development:centos7

      - name: GCC 4.8, C++11
        env:
          CXX_STANDARD: 11
          CXX: g++
          CXX_VERSION: 4.8
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 8, C++17
        env:
          CXX_STANDARD: 17
          CXX: g++
          CXX_VERSION: 8
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 11, C++20
        env:
          CXX_STANDARD: 20
          CXX: g++
          CXX_VERSION: 11
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: Clang 3.4, C++11
        env:
          CXX_STANDARD: 11
          CXX: clang++
          CXX_VERSION: 11
          CC: clang
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: Clang 7, C++17
        env:
          CXX_STANDARD: 17
          CXX: clang++
          CXX_VERSION: 7
          CC: clang
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable llvm-toolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 11, C++17
        env:
          CXX_STANDARD: 17
          CXX: g++
          CXX_VERSION: 11
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 10, C++17
        env:
          CXX_STANDARD: 17
          CXX: g++
          CXX_VERSION: 10
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 9, C++14
        env:
          CXX_STANDARD: 14
          CXX: g++
          CXX_VERSION: 9
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 8, C++14
        env:
          CXX_STANDARD: 14
          CXX: g++
          CXX_VERSION: 8
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 8, C++11
        env:
          CXX_STANDARD: 11
          CXX: g++
          CXX_VERSION: 8
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 7, C++14
        env:
          CXX_STANDARD: 14
          CXX: g++
          CXX_VERSION: 7
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 7, C++11
        env:
          CXX_STANDARD: 11
          CXX: g++
          CXX_VERSION: 7
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-${CXX_VERSION} -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 4.8, C++98
        env:
          CXX_STANDARD: 98
          CXX: g++
          CXX_VERSION: 4.8
          CC: gcc
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake


  build-linux-x86_64-sun:
    name: Linux x86_64 (Sun compiler)
    runs-on: ubuntu-latest
    needs: basic-checks
    # Prevent running this job on fork repos due to the secrets variable
    if: ${{ github.repository_owner == 'Colvars' }} && ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Sun compiler (Oracle Developer Studio)
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/oracle'
          ssh-key: ${{ secrets.PULL_ORACLE_DEVELOPER_STUDIO }}
          ref: 'master'
          path: ${{github.workspace}}/oracle

      - name: Get small downloadable packages
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/build-tools-packages'
          ref: 'master'
          path: 'devel-tools/packages'

      - name: Install Singularity
        shell: bash
        working-directory: devel-tools/packages
        run: |
          sudo apt-get -y install squashfs-tools containernetworking-plugins
          sudo dpkg -i singularity_3.8.5-2_amd64.deb

      - name: Get container image of backends' dependencies
        shell: bash
        working-directory: devel-tools
        run: |
          singularity pull CentOS7-devel.sif library://giacomofiorin/default/colvars_development:centos7

      - name: Build library with Sun compiler (Oracle Developer Studio)
        shell: bash
        env:
          CC: ${{github.workspace}}/oracle/developerstudio12.6/bin/cc
          CXX: ${{github.workspace}}/oracle/developerstudio12.6/bin/CC
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=11 -P devel-tools/build_test_library.cmake


  build-windows-64-msvc:
    name: Windows 64-bit (MSVC)
    runs-on: windows-latest
    needs: basic-checks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:

      - uses: actions/checkout@v2

      - name: Build library with CMake
        # We need to set CMAKE_SYSTEM_NAME manually in script mode
        run: cmake -D CMAKE_SYSTEM_NAME=Windows -P devel-tools/build_test_library.cmake
