name: "Library"

on: [push, pull_request]


jobs:

  basic-checks:

    name: Basic checks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout Colvars
        uses: actions/checkout@v2

      - name: Configure Ccache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-basic-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-basic-

      - name: Install build dependencies for library
        run: |
          sudo apt-get -y install ccache tcl8.6-dev

      - name: Test build recipes
        run: bash devel-tools/check_build_recipes

      - name: Convert BibTeX references to code
        shell: bash
        working-directory: doc
        run: |
          make update-code-refs
          if [ -n "$(git status --porcelain ../src/colvarmodule_refs.h)" ] ; then
              echo "Code citations out of date; please run make update-code-refs in the doc folder" >& 2
              exit 1
          fi

      - name: Build library with CMake
        run: cmake -P devel-tools/build_test_library.cmake

      - name: Check documentation of command-line scripting interface
        shell: bash
        working-directory: doc
        run: |
          make update-cvscript-cmdline-doc
          if [ -n "$(git status --porcelain cvscript-tcl.tex)" ] ; then
              echo "Command-line scripting doc out of date; please run make update-cvscript-cmdline-doc and commit changes" >& 2
              exit 1
          fi


  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    needs: basic-checks
    if: ${{ ! github.event.repository.private }}

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies for library
        run: |
          sudo apt-get -y install tcl8.6-dev
          # OpenMM contains the latest Lepton
          git clone --single-branch --depth=1 https://github.com/openmm/openmm openmm-source

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      - name: Build Colvars library with CMake
        run: cmake -P devel-tools/build_test_library.cmake

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1


  build-linux-x86_64:
    name: Linux x86_64 (many compilers)
    runs-on: ubuntu-latest
    needs: basic-checks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Configure Ccache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-multiple-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-multiple-

      - name: Get small downloadable packages
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/build-tools-packages'
          ref: 'master'
          path: 'devel-tools/packages'

      - name: Install Singularity
        shell: bash
        working-directory: devel-tools/packages
        run: |
          sudo apt-get -y install squashfs-tools containernetworking-plugins
          sudo dpkg -i singularity_3.8.5-2_amd64.deb

      - name: Get container image of backends' dependencies
        shell: bash
        working-directory: devel-tools
        run: |
          singularity pull CentOS7-devel.sif library://giacomofiorin/default/colvars_development:centos7

      - name: GCC 11, C++20
        env:
          CXX_STANDARD: 20
          CXX: g++
          CXX_VERSION: 11
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          scl enable devtoolset-11 -- \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake

      - name: GCC 4.8, C++98
        env:
          CXX_STANDARD: 98
          CXX: g++
          CXX_VERSION: 4.8
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=${CXX_STANDARD} -P devel-tools/build_test_library.cmake


  build-legacy:
    name: Legacy build (pre-C++11 code for VMD)
    runs-on: ubuntu-latest
    needs: basic-checks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Install tcl
        run: sudo apt-get -y install tcl8.6-dev

      - name: Build Colvars
        shell: bash
        run: |
          cmake -D CMAKE_CXX_STANDARD=98 -D WARNINGS_ARE_ERRORS=ON -D CMAKE_VERBOSE_MAKEFILE=ON -D COLVARS_TCL=ON -S ${{github.workspace}}/cmake -B ${{github.workspace}}/build-legacy
          cmake --build ${{github.workspace}}/build-legacy --parallel $(nproc --all)


  build-sunpro:
    name: Sun compiler
    runs-on: ubuntu-latest
    needs: basic-checks
    # Prevent running this job on fork repos due to the secrets variable
    if: ${{ github.repository_owner == 'Colvars' }} && ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Sun compiler (Oracle Developer Studio)
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/oracle'
          ssh-key: ${{ secrets.PULL_ORACLE_DEVELOPER_STUDIO }}
          ref: 'master'
          path: ${{github.workspace}}/oracle

      - name: Get small downloadable packages
        uses: actions/checkout@v2
        with:
          repository: 'Colvars/build-tools-packages'
          ref: 'master'
          path: 'devel-tools/packages'

      - name: Install Singularity
        shell: bash
        working-directory: devel-tools/packages
        run: |
          sudo apt-get -y install squashfs-tools containernetworking-plugins
          sudo dpkg -i singularity_3.8.5-2_amd64.deb

      - name: Get container image of backends' dependencies
        shell: bash
        working-directory: devel-tools
        run: |
          singularity pull CentOS7-devel.sif library://giacomofiorin/default/colvars_development:centos7

      - name: Build library with Sun compiler (Oracle Developer Studio)
        shell: bash
        env:
          CC: ${{github.workspace}}/oracle/developerstudio12.6/bin/cc
          CXX: ${{github.workspace}}/oracle/developerstudio12.6/bin/CC
        run: |
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -E make_directory ${{github.workspace}}/build-sunpro
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 -D CMAKE_CXX_STANDARD=11 -D WARNINGS_ARE_ERRORS=ON -D CMAKE_VERBOSE_MAKEFILE=ON -S ${{github.workspace}}/cmake -B ${{github.workspace}}/build-sunpro
          singularity exec ${{github.workspace}}/devel-tools/CentOS7-devel.sif \
          cmake3 --build ${{github.workspace}}/build-sunpro --parallel $(nproc --all)
