name: "Version maintenance"

on:
  push:
    branches:
      - master

jobs:

  update-wiki:
    name: Update Wiki repo
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Colvars/colvars' }}
    steps:

      - name: Checkout Colvars repo in full
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Checkout Wiki repo
        uses: actions/checkout@v5
        with:
          repository: 'Colvars/colvars.wiki'
          path: 'wiki'

      - name: Cache the SSH key for the runner
        env: 
          SSH_KEY: ${{ secrets.PULL_PUSH_COLVARS_KEY }}
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.email "noreply@github.com"
          git config --global user.name "CI runner"
          
      - name: Update Wiki page that lists Colvars versions
        run: |
          git fetch --all
          bash doc/print_engine_versions.sh > wiki/List-of-Colvars-versions-included-in-simulation-and-analysis-packages.md
          if ! git -C wiki diff --quiet ; then
              git -C wiki add List-of-Colvars-versions-included-in-simulation-and-analysis-packages.md
              git -C wiki commit -m "Update list of Colvars versions"
              git -C wiki push origin master
          fi

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Update "Colvars release notes" Wiki page
        run: |
          ./devel-tools/print_pr_list.py --format notes > wiki/Colvars-release-notes.md
          if ! git -C wiki diff --quiet ; then
              git -C wiki add Colvars-release-notes.md
              git -C wiki commit -m "Update Colvars release notes"
              git -C wiki push origin master
          fi
